[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = TechZone@MasterPass#2026!
db_name = techzone
dbfilter = ^techzone$
list_db = False
proxy_mode = True
